try{
    hello();
} catch (error){
    console.log(error);
}

try{
    anotherfunction();
} catch{
    console.log('Esto es un error')
}